spring:
  application:
    # 应用名称
    name: FamilyServer

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/family?serverTimezone=UTC
    username: family
    password: 10010422ytf

logging:
  level:
    top.gytf.family.server.*: debug

  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %n%msg%n"

server:
  # 运行端口
  port: 8848
