spring:
  application:
    # 应用名称
    name: FamilyServer

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/family?serverTimezone=UTC
    username: family
    password: 10010422ytf

logging:
  level:
    top.gytf.famliy.server.mapper: debug

server:
  # 运行端口
  port: 8848
