spring:
  application:
    # 应用名称
    name: FamilyServer

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/family?serverTimezone=UTC
    username: family
    password: 10010422ytf

  #邮箱配置
  mail:
    #smtp服务主机
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 2632699773@qq.com
    #授权码
    password: nfcmffjcyotoecfe
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    org.springframework.boot.autoconfigure: error
    top.gytf.family.server.*: debug

  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %n%msg%n"

server:
  # 运行端口
  port: 8848

rsa-public-key: "-----BEGIN PUBLIC KEY-----
  MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAOWBCyDclPQ9x3YpwJBKOz5G68yhTU0Z
  ZZXX+flL+3X/0bI8iTHSmHdNI2rLNZhfeGfC5FP4BayjhcRWfvsOU1MCAwEAAQ==
  -----END PUBLIC KEY-----"
rsa-private-key: "-----BEGIN PRIVATE KEY-----
MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEA5YELINyU9D3HdinA
kEo7PkbrzKFNTRllldf5+Uv7df/RsjyJMdKYd00jass1mF94Z8LkU/gFrKOFxFZ+
+w5TUwIDAQABAkBYZgL+TlhFV0JrvhtAuIbnLvQGJp8askyRkdXj8yNRSFQkUZbU
zSqegcP4hbSAtL0pAn8D8zH5xRQ9IeDBZoj5AiEA9Vs7EgkFjq9uliE5cNakTkI8
geCspWlaA+ha7LGm6t8CIQDvdcR0AF35pifEpYE1FtNK3YjReWMl9cvDfhJpOz5a
DQIgcbLfQtJPcvm1A3lOBw5QgbuMEputJdIWVq08RWdl9H0CIQDt83T4YLUBs16p
Rl2Sx8/HAUVIAvvHaOzGoqzg7QIUsQIhAJlsv642KUTGPAfeoZTTlQAtDWTa5cO+
8+rVP1njfWyq
-----END PRIVATE KEY-----"

